### ISSUE TITLE
Where would the synonym 'chemotherapy' live

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/MAxO#124]
In one sense it should be a synonym of pharmacotherapy

but the term is usually used in a cancer context, so a syn of 'antineoplastics agent therapy' might be appropriate?

Either way, I think EXACT would not be appropriate.

Another possibility is to determine the term is too unclear. What I sometimes do here is make an obsolete class with an explanation, that way people searching understand why a bona fide class is not present

**Comment by LCCarmody** [comment]
Definitely open to suggestions.  The hierarchy of the pharmacotherapy branch was chosen based on this https://www.fda.gov/regulatory-information/fdaaa-implementation-chart/usp-therapeutic-categories-model-guidelines

It is helpful but definitely has its drawbacks.  I currently have 'anticancer agent therapy' as a broad synonym. Possibly this could be a parent class with antineoplastic agent therapy and chemotherapy being siblings?  

Just a thought. Will look into other sources for structure suggestions.

**Comment by LCCarmody** [comment]
Will create new term under anti-neoplastic agent therapy

**Comment by LCCarmody** [comment]
I'm revisiting this and thought (initially) it should be a child of anti-neoplastics (see https://github.com/monarch-initiative/MAxO/issues/130).  However, looking more closely at NCIT's definition, I don't think that would work. 
NCIT:C15632 Chemotherapy Def: The use of synthetic or naturally-occurring chemicals for the treatment of diseases.

Comment: Although this term is used to describe any therapy involving the use of chemical-based agents, it is particularly used to refer to the use of chemical-based agents to treat cancer. Antineoplastic chemotherapy works by arresting or killing the growth and spread of cancer cells. Chemotherapy may also include agents that enhance immune function or alter hormonal activity.

I (now) get your point of obsoleting it, but I'm inclined to make it a child of chemotherapy with some explicit notes and a direction to antineoplastics?  What do you think? @cmungall @pnrobinson

**Comment by LCCarmody** [comment]
Trying to update the whole pharmacotherapy branch and this has come up.

It appears that the definition of chemotherapy has significantly shifted over time.  There is the original meaning that @cmungall brought up:  [NCIT](http://purl.obolibrary.org/obo/NCIT_C15632) definition is "The use of synthetic or naturally-occurring chemicals for the treatment of diseases."  

NCIT does have the note: "Although this term is used to describe any therapy involving the use of chemical-based agents, it is particularly used to refer to the use of chemical-based agents to treat cancer. Antineoplastic chemotherapy works by arresting or killing the growth and spread of cancer cells. Chemotherapy may also include agents that enhance immune function or alter hormonal activity."

However, [if you look at cancer.gov where they reference NCI dictionary](https://www.cancer.gov/publications/dictionaries/cancer-terms/def/chemotherapy), they use the definition, "Treatment that uses drugs to stop the growth of cancer cells, either by killing the cells or by stopping them from dividing. Chemotherapy may be given by mouth, injection, or infusion, or on the skin, depending on the type and stage of the cancer being treated. It may be given alone or with other treatments, such as surgery, radiation therapy, or biologic therapy."  

The cancer.gov definition appears to be the current and most used definition.
I'm inclined to use the cancer.gov definition.  The term label could be 'antineoplastic chemotherapy' or 'cancer chemotherapy', HOWEVER, that term almost never used. 

At very least, I think chemotherapy should be a broad synonym, but possibly the term label. Especially since GeneReviews has 184 diseases listed with some sort of reference to chemotherapy (I assume all with the same definition, but I only spot-checked) and there is only one disease referencing 'antineoplastics' at all and zero referencing 'antineoplastic chemotherapy'.  It is hard to check if 'cancer chemotherapy' is in use because of the poor search tool, but I haven't seen it used.   

 Anyone have any opinions? Synonym? Term label? @cmungall @pnrobinson (And @nicolevasilevsky I know you weren't in on this conversation, but if you have an opinion, that'd be great, too.)

**Comment by nicolevasilevsky** [comment]
I feel like chemotherapy is such a commonly used term/treatment that it would be nice if it were its own class. I would recommend 'cancer chemotherapy' as the primary label and 'antineoplastic chemotherapy' as the synonym. 

Although as the NCIt def says, chemotherapy isn't exclusively used for cancer. It can be used for immune system ablation too (like prior to a stem cell transplant).

So maybe you would want a 'chemotherapy' class with 'cancer chemotherapy' as a child? Or 'cancer chemotherapy' as a narrow synonym.
