### ISSUE TITLE
Avoidance of Fava beans

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#136]
This is important for Glucose-6-phosphate dehydrogenase (G6PD) deficiency.
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4571844/

I think this is the reference in foodon
https://www.ebi.ac.uk/ols/ontologies/foodon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFOODON_03301227

@LCCarmody @matentzn  Can we add this for the next release, I am going to put it in the proposal since it is a well known example

**Comment by LCCarmody** [comment]
Yes, we can add this, but--as I noted in the grant text-- this is a redundant portion of the ontology and the branch needs to be significantly reworked.  the screen shot you used is NOT the product of our patterns. I will work to add this term and others and try to do a new release by the end of the week?

**Comment by pnrobinson** [comment]
I made this term in a temporary file and did not save it.
But why is this portion of the ontology redundant?

**Comment by LCCarmody** [comment]
Because that is a branch I created very early manually.  The portion of the food avoidance pattern actually directs the terms under 'nutrition intake' as seen below.  I will have to merge these two branches in some way.  The main issue is that you need to show the below image if you want to say that we are using DOSDP/ODK patterns.

![Screen Shot 2020-01-13 at 12 48 29 PM](https://user-images.githubusercontent.com/26067008/72287669-726a3e80-3615-11ea-9496-d7ec17246eb3.png)

**Comment by LCCarmody** [comment]
This has been implemented.
