### ISSUE TITLE
Additional categories for nutritional supplementation branch?

### ISSUE THREAD

**Issue by laurenechan** [monarch-initiative/MAxO#157]
Looking at the nutritional supplementation branch, it seems like we've gotten a lot added through patterns, which is great! I am wondering if we would find it helpful to add subclass categories for some of these supplementation terms to fit under. For example, we have three terms related to vitamin B12 supplementation:
'methylcobalamin supplementation'
'hydroxocobalamin supplementation'
'cyanocob(III)alamin supplementation'
but we have no general B12 supplementation term as a parent class. As individuals may be recommended a therapeutic B12 supplementation, but no specific type, would we benefit from a broader parent term option like 'vitamin B12 supplementation'?

Similarly we could also create a 'B vitamin supplementation' term for about 8 terms to fall under, but not certain if we have a distinct enough use case for general B vitamin supplementation. We could also re-organize the individual amino acid supplementation under the 'amino acid supplementation' term, but again not necessarily convinced we need it, just wanted to throw it out.

**Comment by laurenechan** [comment]
Other supplementation terms we may consider adding from gene reviews includes:
citrin deficiency
- [ ] sodium pyruvate supplementation

abetalipoproteinemia
- [ ] essential fatty acid supplementation
- [ ] essential fat soluble vitamin supplementation (need A, E and K still)

**Comment by LCCarmody** [comment]
I agree that these should be added, but I am not entirely sure how to go about it. 
The information about terms was taken from [Table 5](http://www.treatable-id.org/resources/literature-review.pdf), which includes the level of granularity that I have added to MAxO.

When building, the pattern, I ended up using CHEBI because all of the terms required were there. (*However, there is a possibility that FOODON would import some of these terms?  That may solve the problem?*).  CHEBI does not have B12 terms as parents for these and FOODON does not have 'methylcobalamin, 'hydroxocobalamin','cyanocob(III)alamin' individually.  Maybe this should be a FOODON ticket?  

This is the [FOODON branch](https://www.ebi.ac.uk/ols/ontologies/foodon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFOODON_03544473&viewMode=All&siblings=false).  It does not have a Vitamin B super class.  I'd have to read up on them to know whether more general vitamin B is a recommended therapy.

**Comment by LCCarmody** [comment]
Finally getting around to this ticket. (Sorry for the delay!) I am making a second food 'nutrition supplementation' pattern and added terms to the original chebi based 'nutrition supplementation' pattern. I have to manually add calcium citrate because it is in neither ontology. Also, for seeing all the amino acids as children of 'amino acid supplementation', you would need to turn on the ELK reasoner and then look at the 'inferred' hierarchy.  This will be added shortly, but will not be available until the next release in December. Thanks!
