### ISSUE TITLE
educational support

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/MAxO#263]
For https://www.ncbi.nlm.nih.gov/books/NBK2591/ 
Arts Syndrome   OMIM:301835 MONDO:0010533
From Gene Reviews:
**Intellectual disability.** An individualized educational support program tailored to the individual’s needs and based on assessment of cognitive abilities should be provided.

should we add a new term 'educational support'?

maybe a child of 'cognitive and behavioral intervention'? or 'supportive care'

**Comment by LCCarmody** [comment]
would this be an 'educational intervention'? And maybe 'early intervention' as a child (with synonym 'birth-to-three')? In this case, I would put it under cognitive and behavioral intervention. There may also be specific autism, ADHD, visual or hearing-specific interventions, too.

**Comment by sabrinatoro** [comment]
Here is my suggestion based on information found (mostly on the cdc.gov website):

Create a parent term that is relatively broad: **Self-management support and education**
  - definition :  assistance provided by clinicians and public health practitioners to enhance an individual and/or their family’s self-efficacy in managing one or more chronic conditions. This assistance can include activities such as patient education, support for lifestyle modifications, and support to help individuals develop the skills needed for effective chronic disease management. 
  - Note: This term implies assistance for chronic conditions. (do we want to keep this? I personally think that it is ok, because it would probably be called something else if it wasn't a chronic condition, maybe "rehabilitation" or something like that). Though they are terms like "Physician Education and Training to Support Breastfeeding", but I don't think it belong here. 
  - reference: https://www.cdc.gov/dhdsp/pubs/guides/best-practices/self-management.htm
 
Children terms: should be only added when there is a specific (and recognized by experts?) program for a specific chronic disease. For example: 
  - **Early Intervention**
      - ​​https://www.cdc.gov/ncbddd/actearly/parents/states.html
      - services and supports that are available to babies and young children with developmental delays and disabilities and their families. These may include speech therapy, physical therapy, and other types of services based on the needs of the child and family. They can have a significant impact on a child’s ability to learn new skills and overcome challenges and can increase success in school and life.
  - **Diabetes self-management education and support (DSMES)**
      - https://www.cdc.gov/diabetes/dsmes-toolkit/index.html

**Comment by pnrobinson** [comment]
+1 but I wonder if "Self-management support and education" should be "Patient health-management support and education" becuase "self-management" can have many different meanings and is ambiguous without more context.

**Comment by LCCarmody** [comment]
@pnrobinson @sabrinatoro sounds good.

**Comment by LCCarmody** [comment]
addressed with latest PR. Closing. thanks for all your help!
