### ISSUE TITLE
NTR: cancer surgery

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/MAxO#337]
**Label**: cancer surgery
**Parent:** surgical procedure

**Def:** Surgical procedures targeted at minimizing or eliminating a neoplastic process.  NCIT:C157740

**xref:** NCIT:C157740

Needed for INCLUDE project

**Comment by LCCarmody** [comment]
Hmmm. This is a nebulous one that is a bit non specific. We have tumorectomy. Would that be enough or do you need a broader term?

**Comment by pnrobinson** [comment]
cancer surgery is a broader term and is a little vague (https://www.mayoclinic.org/diseases-conditions/cancer/in-depth/cancer-surgery/art-20044171). I would suggest we add it as a BROAD synonym to tumorectomy, since that is its primary usage. The same surgery can be considered cancer surgery or not depending on the context (e.g. lymph node removal).

**Comment by nicolevasilevsky** [comment]
I can do this - I'l add the synonym and create a PR, thanks!
