### ISSUE TITLE
ntr: dietary counseling, ntr: medical nutrition therapy

### ISSUE THREAD

**Issue by laurenechan** [monarch-initiative/MAxO#42]
parent: counseling
label: dietary counseling
exact synonym: nutritional counseling, nutrition counseling
definition: Nutrition intervention for nutrition counseling is a supportive process, characterized by a collaborative counselor–patient/client relationship to establish food, nutrition and physical activity priorities, goals, and individualized action plans that acknowledge and foster responsibility for self-care to treat an existing condition and promote health.
Reference: Academy of Nutrition and Dietetics. Nutrition Terminology Reference Manual (eNCPT): Dietetics Language for Nutrition Care 2014, Nutrition Intervention/Terms and Definitions/Nutrition Counseling (C), page-064, http://ncpt.webauthor.com

parent: medical action
label: medical nutrition therapy
exact synonym: MNT
definition: Medical nutrition therapy (MNT) is an evidence-based application of the Nutrition Care Process. The provision of MNT (to a patient/client) may include one or more of the following: nutrition assessment/re-assessment, nutrition diagnosis, nutrition intervention and nutrition monitoring and evaluation that typically results in the prevention, delay or management of diseases and/or conditions.
Reference: Academy of Nutrition and Dietetics. Nutrition Terminology Reference Manual (eNCPT): Dietetics Language for Nutrition Care 2014. http://ncpt.webauthor.com.

orcid: 0000-0002-7463-6306

**Comment by laurenechan** [comment]
If we like MNT as a new class, we can also add subclasses such as 

- nutrition counseling, and subsequent specific counseling e.g. heart healthy diet counseling, DM counseling etc. 
- nutrition support (total parenteral nutrition, enteral nutrition) 
- oral supplement use, (Ensure, Boost etc.)

**Comment by laurenechan** [comment]
@LCCarmody quick question, how does approval/addition of a NTR work? There hasn't been any discussion about these ones, so I wasn't sure if I should move ahead and put in a pull request or just let this one hang around until we've finished pulling literature terms here soon.

**Comment by LCCarmody** [comment]
It is less clear in this ontology because we aren't established yet.  That said, by adding a pull request, you are allowing me (or @pnrobinson ) to review your changes. We can decide to keep your new term or deny it.  To keep from doing too much work, it may be easier to start a new term request and wait for someone to respond.  You can follow up or specifically tag us for a quicker response.

I think dietary counseling shoudl be a term, but I'd like @pnrobinson to weigh in on medical nutrtion therapy.  Also, could you get ISBN # or other sources besides websites?  Websites change, so it is better to get other sources, if possible. Pubmed would be ideal, for this ontology, it will be difficult.

Also, I think you may have to wait for responses. Sorry, we are busy!  Hope you have a couple of additional projects?

**Comment by laurenechan** [comment]
Sounds good, I've got other stuff to plug away at, just trying to get a feel for this work schedule/process!
For updated citations, both of these terms are available within the newest edition of the Nutrition Care Process Terminology Reference Manual, 
ISBN-13: 978-0880919692
ISBN-10: 0880919698

**Comment by LCCarmody** [comment]
Following up on this.  Nutritional counseling should be a term, but I do not think the child term of 'subsequent specific counseling' is necessary.  I do not know what DM counseling is.
Total parenteral nutrition (etc) have already been added.

I am not sure if oral supplementation should be added.  Can you give a specific use case from a rare disease? Also, is there a label that is more specific than 'oral supplementation' because that is vague.  If so, open a separate ticket. Thanks.

**Comment by laurenechan** [comment]
Hi! Looking back at this, 'nutrition counseling' I think is a valid class. The other child classes I was initially considering were 'heart healthy diet counseling' or 'diabetes mellitus counseling' but at this time, I'm not certain those would be a priority to add since they're more common disease focused.

As for oral supplementation, it's definitely a little vague. From my initial NTR request, I think I was more considering a term that represent additional/supplemental calorie consumption through an oral formula. 
i.e. for individuals with maple syrup urine disease, they can use high calorie formula that is low in branched chain amino acids (BCAAs) to provide adequate energy without excess BCAAs.
A similar scenario is seen with Isolated methylmalonic acidemia in which low propiogenic amino acid formulas are given to provide supplemental calories. 

I think a term regarding supplemental oral formulas for extra calorie provision could be widely used (not sure what exact term we would like, maybe 'oral calorie supplementation'?), but we can also make more specific terms that describe oral calorie supplementation through formula with other specific parameters i.e. low BCAAs if that feels more appropriate.
