### ISSUE TITLE
histological procedure

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/MAxO#461]
I am wondering if this should be renamed 'histological examination' because in the context of MAxO we are less interested in the actual procedure (how to staining was done, microtome etc) than in the fact that a pathologist is examing the sample to make a medical interpretation or diagnosis.

**Comment by LCCarmody** [comment]
I'm not wed to the term. Likely used it because of NCIt (which I xreffed) who has histologic examination as an exact synonym.

SNOMED has all similar (though not the exact term) as procedures. Google search leans towards examination. But analysis, test, and procedure are used. I think adding all possible synonyms would be sufficient.

I do have a friend who is director of tissue typing--who I could ask to weigh in.
