### ISSUE TITLE
Initial text mining- Avoid ...

### ISSUE THREAD

**Issue by LCCarmody** [monarch-initiative/MAxO#48]
These are terms that were identified by the initial pass at GeneReviews for 'avoid x'.
The number is the number of times the term was found.  I do not think all of these should be added, but maybe we can come up with some broad categories?  Note: some I did add. We may wish to get rid of them.

@nicolevasilevsky @laurenechan 

avoid the following:	34
the following should be avoided:	30
alcohol	5
dehydration	5
smoking	4
fasting	4
agents	4
valproic acid	3
contact sports, competitive sports, and isometric exercise	3
the following are appropriate:	3
avoidance of sunlight and uv light	3
, estrogens)	3
medications	3
obesity	3
european porphyria network	2
excess protein intake	2
obvious exposure to communicable diseases	2
radiation exposure	2
click here for an up-to-date list	2
blood transfusions	2
in general, activities that traumatize the skin (e	2
see www	2
intramuscular injections	2
diabetes mellitus	2
saffron	2
nuts	2
mussels	2
dark chocolate	2
high meat and seafood intake could exacerbate gout	2
hypertension	2
neuroleptic treatment may exacerbate parkinsonism	2
activities that cause joint injury or pain	2
, scuba diving)	2
circumstances	2
, contact sports)	2
psychological stress	2
hbh disease	1
inappropriate iron therapy	1
oxidant drugs including sulphonamides	1
some antimalarials because of the risk of hemolytic crisis	1
iron supplements	1
affected individuals should avoid medications known to prolong qt intervals	1
see crediblemeds® for a complete and updated list	1
if physiologic stress is unavoidable (e	1
excessive alcohol consumption and smoking should be avoided	1
the drug database for acute porphyria	1
the american porphyria foundation	1
porphyria south africa	1
welsh medicines information centre - porphyria information service	1
british national formulary (subscription required)	1
individuals with liver disease should avoid alcohol consumption	1
sudden changes in environment and over-sedation should be avoided	1
splenectomy as it worsens the hypertriglyceridemia	1
azathioprine should be avoided by individuals taking xdh inhibitors	1
large boluses of protein or amino acids	1
less than recommended intake of protein	1
prolonged fasting or starvation	1
intravenous steroids	1
hepatotoxic drugs in those with hepatic involvement	1
individuals with aved should avoid:	1
occupations requiring quick responses or good balance	1
iron-containing preparations	1
arc welding	1
asbestos	1
unnecessary and prolonged sun exposure	1
the use of rectal thermometers in those with neutropenia	1
diagnostic x-rays should be used sparingly	1
excessive sun exposure increases the likelihood of developing bccs	1
testing of relatives at risk	1
cigarette smoking	1
high ambient pressures, which may precipitate spontaneous pneumothorax	1
febrile state	1
vagotonic agents	1
α-adrenergic agonists [miyazaki et al 1996]	1
β-adrenergic antagonists	1
tricyclic antidepressants	1
first-generation antihistamines (dimenhydrinate)	1
cocaine toxicity	1
class 1c antiarrhythmic drugs including flecainide and propafenone	1
class 1a agents including procainamide and disopyramide	1
excessive dietary fat intake should be avoided	1
stressful emotional and physical situations (e	1
, extreme temperatures)	1
increased doses of glucocorticoids are recommended in these situations	1
potentially exacerbating circumstances:	1
methionine restriction	1
other medications that increase risk of hemorrhage (e	1
see malignant hyperthermia susceptibility for more details	1
activities with a high impact on joints (e	1
, jogging) should be avoided	1
avoid any preparation containing iron	1
no known agents exacerbate the severity of cdls	1
bisphosphonates	1
excess phosphate	1
over-exposure to heat	1
individuals with cfc syndrome report heat intolerance	1
exposures	1
therefore, the following should be avoided:	1
exposure to mulch	1
potting of plants or gardening	1
raking leaves or mowing lawns	1
swimming in stagnant water, brackish water, or ponds	1
transfusion considerations	1
seizure-provoking circumstances (e	1
, sleep deprivation, alcohol intake)	1
anticonvulsants that may worsen involuntary movements (e	1
, carbamazepine, lamotrigine)	1
the following should be noted:	1
baclofen used to treat spasticity can sometimes worsen muscle weakness	1
avoid flickering lights that may provoke seizures	1
all nonsteroidal anti-inflammatory drugs (nsaids) (e	1
low-protein/high-caloric (high-carbohydrate) diet	1
infusion of sugars including glycerol, fructose, and glucose	1
adoii	1
activities with high fracture risk should be avoided	1
obesity because of its negative effect on gait and balance	1
for neuromuscular disorders	1
for skeletal dysplasias	1
excessive sun exposure should be avoided	1
smoking because it increases the global risk of stroke	1
hypertension because it increases the risk of stroke	1
anticoagulant use [gould et al 2006]	1
extended fasting and prolonged exercise are to be avoided	1
valproic acid [kottlors et al 2001]	1
general anesthesia	1
ibuprofen	1
diazepam in high doses [bonnefont et al 1999]	1
dehydration, which compromises remaining renal function	1
sun exposure, which can exacerbate photophobia	1
competitive sports and other strenuous exercise are always contraindicated	1
individuals with dmd/bmd should avoid botulinum toxin injections	1
drugs (e	1
live viral vaccines should be avoided if agammaglobulinemia is present	1
some medications used to treat behavioral problems (e	1
73 m2 (ckd stage 3b)	1
individuals with hearing loss should avoid the following:	1
known environmental factors for hearing loss (e	1
, loud noises)	1
ototoxic medications	1
individuals with ts-nsan	1
avoid excessive body temperatures when possible	1
all blood products should be leukodepleted and irradiated	1
radiation	1
androgens and growth factors	1
cancer prevention	1
catabolic stressors	1
liver-toxic medications	1
general factors that predispose to late-onset diabetes (e	1
discontinuation of levodopa treatment usually results in return of symptoms	1
certain medications may be contraindicated in individuals with arrhythmias	1
see treatment of manifestations	1
seizure triggers (e	1
known triggers of attacks should be avoided	1
phenytoin has been reported to exacerbate symptoms	1
silicone-based products provide a good substitute for tape	1
excessive heat may exacerbate blistering and infection in ebs	1
avoiding activities that traumatize the skin (e	1
obesity, which increases stress on joints	1
exercise that causes repetitive strain on affected joints	1
sports involving joint overload are to be avoided	1
acetylsalicylate (aspirin)	1
joint hyperextension may not need to be avoided	1
resistance exercise can exacerbate joint instability and pain	1
trauma	1
arteriography	1
furthermore, injection pressure may lead to arterial aneurysms	1
routine colonoscopy	1
elective surgery	1
cigarette smoking, which can worsen emphysema	1
sun tanning, which can damage skin	1
contact sports are not advisable in those with splenomegaly	1
in some individuals, exercise can trigger symptoms	1
unsafe sex practices increase the risk for hpv-associated malignancy	1
therefore, affected individuals should be discouraged from smoking	1
surgery and desmoid risk	1
individuals at high risk for desmoids (women	1
those with apc pathogenic variants in codons 1395-1493	1
surgery and fecundity	1
smoking is contraindicated	1
symptoms tend to be worse in hot or humid weather	1
environmental situations associated with hypobaric hypoxia (e	1
cisplatin	1
met694ile [sasaki et al 2009]	1
alcohol can exacerbate ataxia and should be consumed in moderation	1
, rough surfaces) should be avoided	1
further studies are needed to clarify this issue	1
lactose- or galactose-containing drug preparations	1
, ibuprofen)	1
acetaminophen, which is hepatotoxic in overdose	1
barbiturates	1
methylxanthines (e	1
carbonated drinks and alcohol consumption may exacerbate hypocalcemia	1
caffeine intake may contribute to or worsen anxiety	1
3 deletion have reduced perspiration and tend to overheat easily	1
maintain a low-sucrose, low-fructose diet	1
limit galactose and lactose intake to one serving per day	1
hypotension and volume depletion should be avoided	1
exposure to infectious agents is to be avoided	1
long-term steroid usage itself can cause muscle weakness	1
use the following with caution:	1
statins for control of hyperlipidemia	1
beta blockers as they can induce hypoglycemia	1
static muscle contractions (e	1
, handgrip exercises)	1
, weightlifting)	1
dynamic exercises at a high-intensity level (e	1
, competitive ball games)	1
, jumps)	1
very intense dynamic aerobic exercise (e	1
general anesthetics	1
lipid-lowering drugs	1
arg50ter, p	1
liver phk deficiency	1
affected individuals with should avoid the following:	1
prolonged fasting	1
the final decision is based on clinician judgment	1
alcohol, as this may predispose to hypoglycemia	1
muscle phk deficiency	1
affected individuals should avoid the following:	1
vigorous exercise	1
medications that can cause rhabdomyolysis (e	1
, succinylcholine)	1
extreme caloric deprivation (i	1
, total fasting, gastric bypass surgery)	1
female reproductive hormones	1
birth-control pills are risky and not recommended	1
some drugs are clearly unsafe for cpox heterozygotes	1
porphyriafoundation	1
com and www	1
porphyria-europe	1
com	1
any agents that increase ataxia should be used with caution	1
, in individuals with atherosclerotic cardiovascular disease)	1
alcohol consumption in those with hepatic involvement	1
persons of all ages should avoid exposure to sunlight	1
older individuals should avoid the known precipitating factors (e	1
malnutrition	1
infection with human immunodeficiency virus (hiv)	1
immunosuppression (e	1
, after renal transplantation)	1
hepatotoxic medicines should be avoided	1
medicines	1
org	1
not be given to neonates known to have hfi	1
excessive sun exposure, which may exacerbate the rash	1
exposure to heat because of heat intolerance secondary to hypohidrosis	1
physical activity should be self-limited	1
excess dietary protein intake	1
prolonged fasting during an illness or weight loss	1
use of intravenous steroids	1
valproic acid, which exacerbates hyperammonemia in urea cycle disorders	1
exposure to communicable diseases	1
prolonged fasting of any sort should be avoided	1
live vaccinations	1
exposure to infections	1
foods very high in manganese (cloves	1
5 n saline at 1	1
if fluids at 1	1
biphosphonates are relatively contraindicated in hypophosphatasia	1
it is contraindicated in children with hypophosphatasia	1
unusually strenuous effort	1
excess of carbohydrate-rich meals	1
sweets	1
prolonged immobility	1
bleeding	1
pulmonary fibrosis	1
hot or cold environments	1
hot or cold foods	1
hot showers or baths	1
jumping or high-impact activities and sports	1
opiates are contraindicated as this is a chronic disorder	1
l-dopa-containing compounds may increase chorea	1
alcohol and smoking are discouraged	1
fresh frozen plasma should be avoided (i	1
pregnancy	1
some chemotherapeutic agents (e	1
avoid exercise in extreme environmental conditions and maintain adequate hydration	1
use jacuzzis, steam rooms, saunas with caution	1
and avoid the following:	1
medications that decrease afterload (e	1
, ace inhibitors	1
medications for erectile dysfunction (e	1
, sildenafil, tadalafil)	1
the use of other analgesics/antipyretics should be considered	1
exertion under extreme conditions (e	1
see prevention of primary manifestations and prevention of secondary complications	1
high intake of saturated and trans unsaturated fat	1
excessive intake of cholesterol	1
sedentary lifestyle	1
iron-containing preparations and supplemental vitamin c	1
crediblemeds	1
triggers for intense or sudden emotion	1
competitive sports	1
amusement park rides	1
frightening movies	1
jumping into cold water	1
individuals with liver impairment should avoid hepatotoxic medications	1
medications to avoid:	1
carbamazepine [nanba & maegaki 1999]	1
oxcarbazepine [kaddurah & holmes 2006]	1
weight should be controlled to avoid obesity	1
while the specific mechanism whereby cholesterol-lowering agents (e	1
skin irritants and overheating should be avoided	1
corneal contact lenses	1
artificial lens implants	1
large boluses of protein or amino acids should be avoided	1
positive pressure ventilation unless needed to treat life-threatening conditions	1
people with respiratory infections	1
individuals with any degree of hearing loss	1
avoid exposure to ototoxic drugs	1
individuals with cervical spine anomalies	1
individuals with a single kidney	1
manage diabetes mellitus to maintain good control and avoid hyperglycemia	1
caffeine can aggravate a tendency for arrhythmia	1
agents that cause vasoconstriction, including triptans	1
lasik correction of visual deficits	1
alcohol consumption, in particular acute alcohol intoxication (e	1
while a strong association between gsp mutations (i	1
, radiation exposure) and encourage vigilance and monitoring	1
drugs known to be nephrotoxic should be avoided	1
however, patients should avoid chronic daily use	1
about 10% of the individuals with the 15q13	1
3 microdeletion develop schizophrenia	1
phenytoin [eldridge et al 1983]	1
medications known to impair mitochondrial function (e	1
, valproic acid) should be avoided	1
dopamine d2 receptor antagonists (e	1
other medications including monoamine oxidase inhibitors, sympathomimetics (e	1
tobacco and alcohol use	1
medications known to impair mitochondrial function	1
, on a long airplane flight)	1
control weight to avoid obesity	1
stress	1
increased dietary protein	1
risk for malignant hyperthermia	1
depolarizing muscle relaxants (e	1
, succinylcholine) and inhalational agents (e	1
avoid drugs that interfere with mitochondrial function	1
avoid physical trauma to reduce the risk of fractures	1
prolonged fasting can lead to hypoglycemia and should be avoided	1
1555a>g	1
mt-rnr1 pathogenic variant	1
bleeding tendency	1
drugs that inhibit platelet function or blood coagulation:	1
other substances that interfere with platelet function including some antibiotics	1
cardiovascular, psychotropic, and oncologic drugs	1
drugs that affect platelet camp	1
some anesthetics	1
antihistamines	1
hearing loss	1
ototoxic drugs (e	1
exposure to hazardous noise	1
, earplugs, headphones) to attenuate intense sound	1
nephropathy	1
cataract	1
elevation of liver enzymes	1
patients should be aggressively counseled not to smoke	1
avoid sustained fatiguing physical exertion	1
the overall frequency of complications was 8	1
2% (18 of 219)	1
(see malignant hyperthermia susceptibility	1
lamotrigine may exacerbate seizures and myoclonus especially in cln2 disease	1
czp is a sedative and can cause behavior disturbances	1
water intake must not be restricted	1
nephrotoxic agents, e	1
individuals with liver function impairment should avoid hepatotoxic medication	1
no limitations are necessary for most individuals with nf1	1
similarly, unnecessary exposure to ionizing radiation should be avoided	1
author, personal observation]	1
individuals who have splenomegaly should avoid contact sports	1
prolonged unprotected sun exposure should be avoided	1
avoid prolonged exposure of the skin to the sun	1
contact sports should be avoided	1
ideally, children with cchs should not go swimming	1
individuals with an opa1 pathogenic variant are advised:	1
not to smoke	1
to moderate their alcohol intake	1
to use sunglasses to limit uv exposure	1
valproate	1
haloperidol	1
stress, especially physical stress	1
potentially also psychological stress	1
at the same time, preemptive measures (e	1
high-risk activities such as contact sports	1
sdhc, sdhd, sdhaf2, or max	1
the ketogenic diet, which aggravates life-threatening metabolic acidosis	1
for individuals with hearing loss:	1
avoid ototoxic medication such as aminoglycosides if alternatives are available	1
use of central respiratory depressants (e	1
agents that increase risk of glaucoma (e	1
, corticosteroids) are to be avoided	1
avoid:	1
any activity that would potentially increase blood viscosity	1
intravascular volume depletion	1
the importance of maintaining dilute urine cannot be overemphasized	1
excessive ascorbate (i	1
, vitamin c	1
>1000 mg/day)	1
delays in treatment of acute stone episodes	1
nephrotoxic agents	1
marked dietary oxalate excess	1
high-dose ascorbic acid	1
, pain, deformity) are significant	1
inactive, sedentary lifestyle	1
exposure to medications or chemicals that exacerbate neuropathy	1
foods that are likely to lead to choking	1
medications acting on d2 receptor blockers (e	1
susceptibility factors (if known) (e	1
exposure to sunlight in symptomatic phase	1
appetite-suppressant medications (e	1
hypoxia	1
avoid immobilization (e	1
, casting)	1
neuroleptic antiemetics (e	1
anchovies, sardines) in excess	1
dehydration worsens episodes of acute pancreatitis	1
f2 20210g>a heterozygotes:	1
participation in such activities should be discouraged	1
there is no known reason to avoid vaccinations	1
rdp	1
fever	1
excessive exercise (such as running track)	1
ahc	1
emotional excitement	1
excessive or atypically strenuous exercise (e	1
illness	1
irregular sleep, missing a nap, delayed bedtime	1
capos syndrome	1
prokinetic agents (e	1
, cisapride)	1
antipsychotics (e	1
, thioridazine), tricyclic antidepressants (e	1
, imipramine)	1
antiarrhythmics (e	1
, quinidine, sotolol, amiodarone)	1
anesthetic agents (e	1
, thiopental, succinylcholine)	1
antibiotics (e	1
, erythromycin, ketoconazole)	1
avoid dietary restriction of riboflavin	1
no adverse drug effects have been documented in rotor syndrome	1
the list includes:	1
ezetimibe	1
anticancer drugs - methotrexate and irinotecan	1
sartans – olmesartan and valsartan	1
rifampicin	1
mycophenolic acid	1
torsemide	1
thiazolidine diones – pioglitazone and rosiglitazone	1
glinides – nateglinide and repaglinide	1
lopinavir	1
fexofenadine	1
vitamin e may adversely affect the course of rp	1
, 400 iu/d) [berson 2000]	1
pregnancy management	1
lifestyle modifications are advised based on genotype	1
ibuprofen (brufen®):	1
give with care in those with evidence of cardiomyopathy	1
avoid in those with congestive heart failure	1
, diphenylhydantoin)	1
alcohol and sedating drugs can exacerbate ataxia	1
alcohol and sedation may make gait and coordination worse	1
, isoniazid)	1
, salicilates)	1
environmental noise at work and in everyday life (e	1
affected individuals should get plenty of rest	1
symptoms are often aggravated by fatigue	1
some drugs (e	1
activities that cause joint pain or injury	1
environmental controls include avoiding the following:	1
extremes of temperature (e	1
physical exhaustion	1
extremely high altitude without oxygen supplementation	1
cocaine	1
heat, stress, and lack of sleep	1
vaccinations with live vaccines	1
anti-cancer therapies	1
environmental manganese exposure (i	1
high manganese content of total parenteral nutrition	1
foods very high in manganese, including: cloves	1
and pumpkin, sesame, and sunflower seeds	1
drugs with anti-dopaminergic side effects (e	1
significant changes in her sleep pattern were also documented	1
neuroleptics and other dopamine antagonists (e	1
, metoclopramide)	1
the refractory epilepsy was finally controlled with magnesium valproate	1
in addition, the eeg demonstrated improved background organization	1
margarines and other products containing stanols (e	1
medications that cause renal or otic toxicity should be avoided	1
medicinal iron	1
mineral supplements	1
excess vitamin c	1
aspiration of food should be avoided to prevent pneumonia	1
drugs and dietary practices that could lead to hypoglycemia	1
avoid or eat in moderation	1
drugs that are metabolized by the fmo3 enzyme	1
for example, the antipsychotic clozapine	1
the monoamine oxidase b inhibitor deprenyl	1
the anti-histamine ranitidine	1
the anti-estrogen tamoxifen	1
these compete for residual fmo3 activity	1
avoid the following	1
estrogen use in adolescent and adult females	1
nephrectomy (see treatment of manifestations, renal angiomyolipoma)	1
avoid inappropriate protein intake	1
heavy muscle force training of weak muscles should be avoided	1
they should therefore exercise caution while swimming	1
myocardial irritation (e	1
, cardiac catheterization)	1
dehydration (risk for acute tubular necrosis)	1
agents known to predispose to hvod (e	1
smoking and excess weight increase the risk of atherosclerosis	1
trauma to the extremities should be avoided	1
individuals with severe hypohidrosis can have marked heat intolerance	1
live vaccines	1
transfusion of non-irradiated blood products	1
artificial sources of uv	1
certain light sources (e	1
cigarette smoke	1
individuals with zap70-related cid should avoid the following:	1
non-irradiated blood products	1
live virus vaccinations	1
contaminated water sources	1
exposure to fungus-enriched environments (e	1

**Comment by laurenechan** [comment]
[Nutrition avoidance MAXO.xlsx](https://github.com/monarch-initiative/MAxO/files/3432606/Nutrition.avoidance.MAXO.xlsx)

Here's some initial findings I have from FOODON or other ontologies to address our avoidance terms. Most of these are likely appropriate for a DOSDP pattern for food_intake_aviodance (I think that's what we had determined for our term choice?). Others may need additional consideration as they relate to either micro or macronutrients and are not a distinct food.

**Comment by LCCarmody** [comment]
Github doesn't support excel files and I cannot read this. Can you attach a txt or tsv? I believe copy and paste will give markdown format as well.

**Comment by laurenechan** [comment]
Sorry about that, I think I knew that but didn't remember which format it did like. 

[Nutrition avoidance MAXO.txt](https://github.com/monarch-initiative/MAxO/files/3432780/Nutrition.avoidance.MAXO.txt)

**Comment by laurenechan** [comment]
INITIAL   QUERY- MACRO avoid | FOODON_# | FOODON_term_name | FOODON_def | Other ontology | Other_term_name | Other_def |   |  
-- | -- | -- | -- | -- | -- | -- | -- | --
excess protein intake    2 | FOODON_03420236 | protein | Extract, concentrate or isolate high in protein; may contain amino acids,   polypeptides and enzymes. Includes casein, gelatin, and gluten. | CHEBI_36080 | protein | A biological macromolecule minimally   consisting of one polypeptide chain synthesized at the ribosome.
excess dietary protein intake    1 |   |   |   |   |   |   |   |  
large boluses of protein or amino   acids    1 |   |   |   |   |   |   |   |  
large   boluses of protein or amino acids should be avoided    1 |   |   |   |   |   |   |  
increased dietary protein    1 |   |   |   |   |   |   |   |  
avoid inappropriate protein intake    1 |   |   |   |   |   |   |   |  
less than recommended intake of   protein    1 |   |   |   |   |   |   |   |  
methionine restriction    1 |   |   |   | CHEBI_16811 | methionine | A sulfur-containing amino acid that   is butyric acid bearing an amino substituent at position 2 and a methylthio   substituent at position 4.
  |   |   |   |   |   |   |   |  
excessive dietary fat intake should be   avoided    1 | FOODON_03420190 | fat or oil | Food substance or component consisting predominantly of mixed glycerol   esters of fatty acids and, in far lesser amounts, of fatty acids, sterols and   pigments. A fat is a solid at room temperature, an oil is a liquid at room   temperature (20 degrees C.). Ex | CHEBI_35366 | fatty acid | Any aliphatic monocarboxylic acid   derived from or contained in esterified form in an animal or vegetable fat,   oil or wax.
high intake of saturated and trans   unsaturated fat    1 |   |   |   | CHEBI_26607, NCIT_C68421 | saturated fatty acid | Any fatty acid containing no carbon   to carbon multiple bonds. Known to produce adverse biological effects when   ingested to excess.
  |   |   |   | NCIT_C68440 | trans fatty acid | A class of dietary fatty acids   containing at least one double bond in the trans formation., A type of fat   that has certain chemical properties and is usually found in processed foods   such as baked goods, snack foods, fried foods, shortening, margarine, an
  |   |   |   |   |   |   |   |  
excessive intake of cholesterol    1 |   |   |   | CHEBI_16113 | cholesterol | A cholestanoid consisting of   cholestane having a double bond at the 5,6-position as well as a   3beta-hydroxy group.
  |   |   |   | OMIT_0004111 | cholesterol,dietary | none? |   |  
low-protein/high-caloric   (high-carbohydrate) diet    1 | FOODON_03510060 | high energy food | none? | CHEBI_16646 | carbohydrate | Any member of the class of   organooxygen compounds that is a polyhydroxy-aldehyde or -ketone or a lactol   resulting from their intramolecular condensation (monosaccharides);   substances derived from these by reduction of the carbonyl group (alditols),   by oxi
  |   |   |   | CMO_0002651 | total calorie intake level | The entire number of calories, i.e.   the total amount of energy, consumed by an organism, regardless of source.
excess of carbohydrate-rich meals    1 |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |  
infusion of   sugars including glycerol, fructose, and glucose    1 |   |   | CHEBI_17754 | glycerol | A triol with a structure of propane   substituted at positions 1, 2 and 3 by hydroxy groups.
  | FOODON_03316754 | fructose | none? | CHEBI_28757 | fructose | A ketohexose that is an isomer of   glucose.
  |   |   |   | CHEBI_17234 | glucose | An aldohexose used as a source of   energy and metabolic intermediate.
maintain a low-sucrose, low-fructose   diet    1 | FOODON_03316754 | fructose | none? |   |   |   |   |  
  |   |   |   | CHEBI_17992 | sucrose | Sucrose is a disaccharide formed by   glucose and fructose units joined by an acetal oxygen bridge from hemiacetal   of glucose to the hemiketal of the fructose.
limit   galactose and lactose intake to one serving per day    1 |   |   | CHEBI_28260 | galactose | An aldohexose that is the C-4 epimer   of glucose.
  |   |   |   | CHEBI_17716 | lactose | A glycosylglucose disaccharide,   found most notably in milk, that consists of D-galactose and D-glucose   fragments bonded through a beta-1->4 glycosidic linkage. The glucose   fragment can be in either the alpha- or beta-pyranose form, whereas the   galactose f
  |   |   |   |   |   |   |   |  
INITIAL QUERY- MICRO avoid | FOODON_# | FOODON_term_name | FOODON_def | CHEBI_# | CHEBI_term_name | CHEBI_def |  
iron supplements    1 | FOODON_03401301 | single mineral supplement | A single mineral supplement is defined as containing one mineral, e.g.   calcium supplement. | CHEBI_18248 | iron | An iron group element atom that has   formula Fe. An iron group element that has formula Fe.
iron-containing preparations    1 | FOODON_03401300 | multi-mineral supplement | A multi-mineral supplement contains   more than one mineral, e.g. calcium-magnesium supplement.
medicinal iron    1 |   |   |   |   |   |   |   |  
inappropriate iron therapy    1 |   |   |   |   |   |   |   |  
avoid any preparation containing   iron    1 |   |   |   |   |   |   |   |  
iron-containing preparations and   supplemental vitamin c    1 | FOODON_03413763 | vitamin c | no def | CHEBI_21241 | vitamin c | none |   |  
excessive ascorbate (i    1 |   |   |   | CHEBI_22652 | ascorbic acid | none |   |  
high-dose ascorbic acid    1 |   |   |   |   |   |   |   |  
excess vitamin c    1 |   |   |   |   |   |   |   |  
, vitamin c    1 |   |   |   |   |   |   |   |  
excess phosphate    1 | NCIT_C68277 | dietary phosphorus |   | CHEBI_26020 | phosphate | Salts and esters of phosphoric and   oligophosphoric acids and their chalcogen analogues. In inorganic chemistry,   the term is also used to describe anionic coordination entities with   phosphorus as central atom.
foods very high in manganese (cloves    1 |   |   |   | NCIT_C68266 | dietary manganese | Forms of the element manganese found   in foods.
  | FOODON_03541323 | cloves buds | Spices from the buds of the plant   classified under the species Syzygium aromaticum (L.). Merr. & Perr or   Eugenia caryophyllata or Caryophyllus aromaticus L., commonly known as Cloves   buds. The part consumed/analysed is not specified. When relevant, inform
high manganese content of total   parenteral nutrition    1 | FOODON_03430169 | parenteral preparation | Parenteral preparations are not   dietary supplements per se, but are included in this classification because   of their importance in nutrient intake. Parenteral preparations are sterile,   pyrogen-free liquids (solutions, emulsions, or suspensions) or solid d
marked dietary oxalate excess    1 |   |   |   | CHEBI_132952 | oxalates | A dicarboxylic acid anion obtained   by deprotonation of at least one of the carboxy groups of oxalic acid.
  |   |   |   | NCIT_C82078 | oxalates | A salt or ester of oxalic acid.
avoid dietary restriction of   riboflavin    1 | FOODON_03544476 | vitamin b2 | The group includes Vitamin B2 used for fortification or enrichment of   foods. Riboflavin, also known as vitamin B2, is the vitamin formerly known as   G. It is an easily absorbed colored micronutrient with a key role in   maintaining health in humans and other | CHEBI_17015 | riboflavin | D-Ribitol in which the hydroxy group   at position 5 is substituted by a   7,8-dimethyl-2,4-dioxo-3,4-dihydrobenzo[g]pteridin-10(2H)-yl moiety. It is a   nutritional factor found in milk, eggs, malted barley, liver, kidney, heart,   and leafy vegetables, but the
mineral supplements    1 | FOODON_03401300 | multi-mineral supplement | A multi-mineral supplement contains   more than one mineral, e.g. calcium-magnesium supplement.
  |   |   |   |   |   |   |   |  
INITIAL QUERY- SPECIFIC   FOOD/GROUP avoid |   |   |   |   |   |   |   |  
alcohol      5 | FOODON_03310661 | beverage alcohol | none | CHEBI_30879 | alcohol | A compound in which a hydroxy group,   -OH, is attached to a saturated carbon atom.
to moderate their alcohol intake    1 | FOODON_03302013 | food containing alcohol | none | NCIT_C2190 | alcohol | A volatile liquid prepared by   fermentation of certain carbohydrates. Alcohol acts as a central nervous   system (CNS) depressant, a diuretic, and a disinfectant. Although the exact   mechanism of CNS depression is unknown, alcohol may act by inhibiting the op
saffron      2 | FOODON_03301867 | saffron (ground) | none |   |   |   |   |  
  | FOODON_03411459 | saffron (plant) | none |   |   |   |   |  
  | FOODON_03541288 | saffron | Spices from the flower pistil of the   plant classified under the species Crocus sativus L., commonly known as   saffron. The part consumed/analysed is not specified. When relevant,   information on the part consumed/analysed has to be reported with additional
nuts      2 | FOODON_03301367 | nuts (mixed) | none |   |   |   |   |  
  | FOODON_03510221 | nuts and products thereof | none |   |   |   |   |  
mussels      2 | FOODON_03411223 | mussel | Mussel is the common name used for   members of several families of bivalve molluscs, from saltwater and   freshwater habitats. These groups have in common a shell whose outline is   elongated and asymmetrical compared with other edible clams, which are often m
anchovies, sardines) in excess    1 | FOODON_03542405 | anchovies (esfa foodex2) | Marine fishes classified under the   species Engraulis encrasicolus or Engraulis japonicus or Engraulis mordax or   Engraulis capensis, commonly known as Anchovies. The part consumed/analysed   is not specified. When relevant, information on the part consumed/a
  | FOODON_03542630 | canned anchovies | The group includes any type of   Canned anchovies. The part consumed/analysed is by default the whole, or a   portion representing the heterogeneity observed in the product. When   relevant, information on the part consumed/analysed has to be reported with   addi
  | FOODON_03542401 | herrings, sardines, anchovies | The group includes any type of   marine fish belonging to the ISSCAAP group 35: Herrings, sardines, anchovies.   ] and [https://www.google.co.uk/search?tbm=isch&q=edible fish Herrings,   sardines, anchovies]
high meat and seafood intake could   exacerbate gout    2 | FOODON_03315240 | meat (solid) | none |   |   |   |   |  
  | FOODON_00001006 | meat food product | A food product made of meat, the   skeletal muscle and associated fat, and other edible tissues such as organs,   livers, skin, brains, bone marrow, kidneys, or lungs, of mammals. [
  | FOODON_00001046 | seafood product | A seafood product is a vertebrate or   invertibrate organism from anaquatic environment.
dark chocolate    2 | FOODON_03303588 | dark chocolate | none |   |   |   |   |  
sweets      1 | FOODON_03316428 | sweets | none |   |   |   |   |  
hot or cold foods    1 |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |  
water intake must not be restricted    1 | FOODON_00002340 | water (food product) | none | ENVO_00003064 | drinking water | Drinking water is water which may be   consumed by humans with no adverse effects on their health.
foods very high in manganese, including:   cloves    1 |   |   |   | NCIT_C68266 | dietary manganese | Forms of the element manganese found   in foods.
  | FOODON_03541323 | cloves buds | Spices from the buds of the plant   classified under the species Syzygium aromaticum (L.). Merr. & Perr or   Eugenia caryophyllata or Caryophyllus aromaticus L., commonly known as Cloves   buds. The part consumed/analysed is not specified. When relevant, inform
and pumpkin, sesame, and sunflower   seeds    1 | FOODON_03304870 | pumpkin seed (shelled) | none |   |   |   |   |  
  | FOODON_00002232 | sesame food product |   |   |   |   |   |  
  | FOODON_03310306 | sesame seed |   |   |   |   |   |  
  | FOODON_03304876 | sesame seed (hulled) |   |   |   |   |   |  
  | FOODON_03304874 | sesame seed (roasted) |   |   |   |   |   |  
  | FOODON_03304154 | sesame seed (paste) |   |   |   |   |   |  
  | FOODON_03304869 | sunflower seed (raw) |   |   |   |   |   |  
  | FOODON_03309990 | sunflower seed (shelled) |   |   |   |   |   |  
margarines and other products containing   stanols (e    1 | FOODON_00002022 | margarine food product |   | DRON_00016316 | plant stanol ester |   |  
  |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |

**Comment by LCCarmody** [comment]
Now the excel files are showing up. Weird. Okay thanks, I will take a look. best.

**Comment by LCCarmody** [comment]
Closing this as nearly all are in other tickets or have been added.
