### ISSUE TITLE
Consider patterns for importing definitions from external sources

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/MAxO#52]
Rather than manually asserting definitions from external sources, we should create an update script.

def: x {xref: external}

**Comment by LCCarmody** [comment]
I'm super proud of myself for writing a python script to extract these!  The work on this doesn't need to be done anytime soon... BECAUSE I WROTE A SCRIPT AND CAN DO IT ANYTIME I LIKE! :)   Anyways, these are the ones I found:
'MAXO_0000001'] ['OGMS:0000096']
['MAXO_0000002'] ['NCIT:C49236']
['MAXO_0000003'] ['NCIT:C18020']
['MAXO_0000004'] ['NCIT:C15329']
['MAXO_0000005'] ['NCIT:C17369']
['MAXO_0000011'] ['NCIT:C15302']
['MAXO_0000014'] ['NCIT:C15313']
['MAXO_0000015'] ['NCIT:C15187']
['MAXO_0000031'] ['NCIT:C95171']
['MAXO_0000058'] ['CHEBI:52217']
['MAXO_0000065'] ['NCIT:C39774']
['MAXO_0000066'] ['NCIT:C94624']
['MAXO_0000068'] ['NCIT:C15342']
['MAXO_0000076'] ['NCIT:C74954']
['MAXO_0000077'] ['NCIT:C61547']
['MAXO_0000077'] ['NCIT:C61547']
['MAXO_0000078'] ['NCIT:C150658']
['MAXO_0000079'] ['NCIT:C15240']
['MAXO_0000081'] ['NCIT:C101244']
['MAXO_0000083'] ['NCIT:C15176']
['MAXO_0000084'] ['NCIT:C51975']
['MAXO_0000085'] ['NCIT:C64897']
['MAXO_0000086'] ['NCIT:C15204']
['MAXO_0000087'] ['NCIT:C15276']
['MAXO_0000088'] ['NCIT:C15447']
['MAXO_0000090'] ['NCIT:C93322']
['MAXO_0000106'] ['NCIT:C15425']
['MAXO_0000107'] ['NCIT:C1654']
['MAXO_0000112'] ['NCIT:C67025']
['MAXO_0000113'] ['NCIT:C73430']
['MAXO_0000114'] ['NCIT:C29484']
['MAXO_0000117'] ['NCIT:C37932']
['MAXO_0000117'] ['NCIT:C37932']
['MAXO_0000118'] ['NCIT:C15258']
['MAXO_0000124'] ['NCIT:C15419']
['MAXO_0000125'] ['NCIT:C38036']
['MAXO_0000126'] ['NCIT:C15406']
['MAXO_0000127'] ['NCIT:C15709']
['MAXO_0000128'] ['NCIT:C92721']
['MAXO_0000130'] ['NCIT:C16546']
['MAXO_0000130'] ['NCIT:C16546']
['MAXO_0000133'] ['NCIT:C64865']
['MAXO_0000134'] ['NCIT:C116476']
['MAXO_0000136'] ['NCIT:C116480']
['MAXO_0000137'] ['NCIT:C17007']
['MAXO_0000137'] ['NCIT:C17007']
['MAXO_0000138'] ['NCIT:C148281']
['MAXO_0000139'] ['NCIT:C25153']
['MAXO_0000140'] ['NCIT:C49132']
['MAXO_0000141'] ['NCIT:C17348']
['MAXO_0000141'] ['NCIT:C17348']
['MAXO_0000141'] ['NCIT:C17348']
['MAXO_0000141'] ['NCIT:C17348']
['MAXO_0000142'] ['NCIT:C16192']
['MAXO_0000143'] ['NCIT:C94473']
['MAXO_0000144'] ['NCIT:C16680']
['MAXO_0000146'] ['NCIT:C48938']
['MAXO_0000147'] ['NCIT:C49286']
['MAXO_0000148'] ['NCIT:C96614']
['MAXO_0000149'] ['NCIT:C64796']
['MAXO_0000149'] ['NCIT:C64796']
['MAXO_0000149'] ['NCIT:C64796']
['MAXO_0000164'] ['NCIT:C29733']
['MAXO_0000173'] ['CHEBI:50919']
['MAXO_0000187'] ['CHEBI:35530']
['MAXO_0000191'] ['CHEBI:35620']
['MAXO_0000197'] ['CHEBI:23066']
['MAXO_0000213'] ['NCIT:C667']
['MAXO_0000213'] ['NCIT:C667']
['MAXO_0000220'] ['CHEBI:24261']
['MAXO_0000230'] ['NCIT:C1590']
['MAXO_0000230'] ['CHEBI:22333']
['MAXO_0000233'] ['NCIT:C15183']
['MAXO_0000239'] ['CHEBI:35443']
['MAXO_0000259'] ['NCIT:C581']
['MAXO_0000269'] ['CHEBI:37961']
['MAXO_0000272'] ['NCIT:C29723']
['MAXO_0000296'] ['CHEBI:50847']
['MAXO_0000297'] ['CHEBI:35705']
['MAXO_0000312'] ['NCIT:C78273']
['MAXO_0000323'] ['CHEBI:35717']
['MAXO_0000424'] ['NCIT:C16809']
['MAXO_0000429'] ['NCIT:C15751']
['MAXO_0000430'] ['NCIT:C15195']
['MAXO_0000434'] ['CHEBI:38215']
['MAXO_0000436'] ['CHEBI:60643']
['MAXO_0000439'] ['NCIT:C94725']
['MAXO_0000439'] ['NCIT:C94725']
['MAXO_0000440'] ['NCIT:C387']
['MAXO_0000445'] ['CHEBI:48675']
['MAXO_0000446'] ['CHEBI:4450']
['MAXO_0000450'] ['NCIT:C48601']
['MAXO_0000451'] ['NCIT:C51982']
['MAXO_0000453'] ['NCIT:C111241']
['MAXO_0000454'] ['NCIT:C111157']
['MAXO_0000455'] ['NCIT:C15215']
['MAXO_0000456'] ['NCIT:C15670']
['MAXO_0000460'] ['NCIT:C38068']
['MAXO_0000466'] ['NCIT:C51969']
['MAXO_0000467'] ['NCIT:C51913']
['MAXO_0000468'] ['NCIT:C159340']
['MAXO_0000479'] ['NCIT:C16186']
['MAXO_0000489'] ['NCIT:C49672']
['MAXO_0000492'] ['NCIT:C49678']
['MAXO_0000499'] ['NCIT:C15322']
['MAXO_0000511'] ['NCIT:C124039']
['MAXO_0000512'] ['NCIT:C124040']
['MAXO_0000517'] ['NCIT:C37981']
['MAXO_0000518'] ['NCIT:C50819']
['MAXO_0000527'] ['NCIT:C20989']
['MAXO_0000528'] ['NCIT:C92714']
['MAXO_0000534'] ['NCIT:C52009']
['MAXO_0000535'] ['NCIT:C15631']
['MAXO_0000536'] ['NCIT:C92755']
['MAXO_0000537'] ['NCIT:C92740']
['MAXO_0000538'] ['NCIT:C92786']
['MAXO_0000539'] ['NCIT:C92805']
['MAXO_0000540'] ['NCIT:C92837']
['MAXO_0000541'] ['NCIT:C92865']
['MAXO_0000543'] ['NCIT:C64550']
['MAXO_0000544'] ['NCIT:C96654']
['MAXO_0000545'] ['NCIT:C64470']
['MAXO_0000546'] ['NCIT:C51949']
['MAXO_0000567'] ['NCIT:C92744']
['MAXO_0000568'] ['NCIT:C41376']
['MAXO_0000569'] ['NCIT:C80400']
['MAXO_0000571'] ['NCIT:C17204']
['MAXO_0000573'] ['NCIT:C94631']
['MAXO_0000574'] ['NCIT:C146918']
['MAXO_0000580'] ['NCIT:C74685']
['MAXO_0000585'] ['NCIT:C25300']
['MAXO_0000589'] ['NCIT:C20055']
['MAXO_0000590'] ['NCIT:C102661']
['MAXO_0000602'] ['NCIT:C15248']
['MAXO_0000603'] ['NCIT:C15297']
['MAXO_0000604'] ['NCIT:C74971']
['MAXO_0000605'] ['NCIT:C64430']
['MAXO_0000606'] ['NCIT:C103430']
['MAXO_0000608'] ['NCIT:C61028']
['MAXO_0000610'] ['NCIT:C16553']
['MAXO_0000615'] ['NCIT:C17638']
['MAXO_0000616'] ['NCIT:C60832']
['MAXO_0000617'] ['NCIT:C38085']
['MAXO_0000620'] ['NCIT:C40972']
['MAXO_0000624'] ['NCIT:C15286']
['MAXO_0000646'] ['NCIT:C15632']
['MAXO_0000647'] ['NCIT:C15632']
['MAXO_0000647'] ['NCIT:C15632']
['MAXO_0000653'] ['NCIT:C66930']
['MAXO_0000653'] ['NCIT:C66930']
['MAXO_0000726'] ['NCIT:C38066']
['MAXO_0000727'] ['NCIT:C99535']
['MAXO_0000728'] ['NCIT:C17644']
['MAXO_0000729'] ['NCIT:C18315']
['MAXO_0001000'] ['NCIT:C17958']
['MAXO_0001005'] ['CHEBI:60605']
['MAXO_0001006'] ['NCIT:C28133']
['MAXO_0001007'] ['NCIT:C51946']
['MAXO_0001008'] ['NCIT:C51951']
['MAXO_0001010'] ['NCIT:C51948']
['MAXO_0001017'] ['NCIT:C15258']
['MAXO_0001019'] ['NCIT:C92860']
['MAXO_0001022'] ['CHEBI:35471']
['MAXO_0001026'] ['CHEBI:35522']

**Comment by matentzn** [comment]
Hahha you are the best! Thats the spirit!

**Comment by mellybelly** [comment]
@LCCarmody you rock!

**Comment by LCCarmody** [comment]
aw, shucks. Now I'm a bit embarrassed. :)

**Comment by pnrobinson** [comment]
awesome, @LCCarmody !

**Comment by matentzn** [comment]
From call:

1. robot query -i mirror/ncit.owl --query ../sparql/term_definitions.sparql ncit_definitions.tsv
2. robot query -i maxo-edit.owl --query ../sparql/maxo_classes_with_definitions.sparql maxo_classes_with_definitions.txt

Removing all definitions based on NCIT in maxo
3. robot remove -i maxo-edit.owl -T maxo_classes_with_definitions.txt --term IAO:0000115 --signature true -o maxo-edit.owl.tmp.owl && mv maxo-edit.owl.tmp.owl maxo-edit.owl

5. Write script that takes as an input ncit_definitions.tsv and produces a new table that looks like this:

MAXO:001 "some ncit definition"
MAXO:002 "some other ncit definition"

we turn this table into a ROBOT template that can now be translated into OWL, and then merged into maxo-edit.owl. i will help you with this!

**Comment by matentzn** [comment]
http://robot.obolibrary.org/template

**Comment by matentzn** [comment]
tip: check out src/sparql/xrefs.sparql and see whether you can modify it to do step 1!
