### ISSUE TITLE
NTR: ovarian cystectomy

### ISSUE THREAD

**Issue by twhetzel** [monarch-initiative/MAxO#602]
ntr: ovarian cystectomy

parent: 'surgical excision', MAXO:0000447

def: The surgical removal (cutting out) of a cyst from the ovary.

needed for INCLUDE
cc @lopierra

Note: I considered `cystectomy` (MAXO:0001044) as a parent, but I see that this is defined in MAxO and elsewhere [1] as the removal of all or part of the _bladder_.

[1] https://uvahealth.com/services/urology/cystectomy

**Comment by LCCarmody** [comment]
Yes, unfortunately, the same word is used for both and OLS doesn't explicitly state that it is a separate comment.  Probably this should be a a pattern where there is removal of a cyst from numerous locations.

**Comment by twhetzel** [comment]
As ontologists, yes separating "the removal of a cyst" from the "location of where the cyst is" would be a nice pattern. However, based on a few references (one linked above) it seems the nomenclature for "cystectomy" is related to only the bladder.

**Comment by monicacecilia** [comment]
@LCCarmody - Will you work on these changes? Or are you saying that there is nothing that can be done? 
Thanks!

**Comment by LCCarmody** [comment]
Yes, I am saying it will be done, but it isn't as straight forward as the original query suggests. Since the word is used for 2 totally different medical action, a decision would have to be made at how to distinguish the 2 sufficiently. Removal of cyst should not be child of current term cystectomy. 

Likely suggestions is that neither term should be called cystectomy--but should be removal of bladder or cyst as appropriate and a comment be made in each about the overlap in the naming.

**Comment by LCCarmody** [comment]
added terms to surgical excision branch. Did not create a pattern, but it is possible to do so in the future.
