### ISSUE TITLE
hormone replacement therapy and others

### ISSUE THREAD

**Issue by diatomsRcool** [monarch-initiative/MAxO#90]
I need terms to represent someone taking the following medication types:

- [x] hormone replacement therapy
- [x] - aspirin therapy
- [x] - ACE INHIBITORS (subclass of pulmonary antihypertensives)
- [x] - ALPHA-GLUCOSIDASE INHIBITORS (sublcass of antidiabetic agents) prevent digestion of carbs
- [x] - BILE-ACID SEQUESTRANTS (subclass of hypolipidemic agents)
- [x] - BENZODIAZEPINES (somewhere under psychotropic agents? CHEBI:22720)
- [x] - T-TYPE CALCIUM-CHANNEL BLOCKER (subclass of calcium channel blocker)
- [x] - SLOW-RELEASE DIHYDROPYRIDINES OTHER THAN NIFEDIPINE OR AMLOPIDINE (L-type calcium channel blocker - subclass of calcium channel blocker)
- [x] - ERECTILE DYSFUNCTION DRUGS (PDE5 inhibitor?)
- [x] - FIBRATES (subclass of dyslipidemic agent)
- [x] - K-CHANNEL BLOCKERS TO ENHANCE INSULIN SECRETION FOR DIABETICS (add a potassium channel blocker class? add as subclass of antidiabetic agent?)
- [x] - POTASSIUM SUPPLEMENTS (subclass of nutritional supplementation)
- [x] - POTASSIUM-SPARING AGENTS ALONE (subclass of diuretic?)
- [x] - LOOP DIURETICS (sublass of diuretic?)
- [x] - NIACIN AND NICOTINIC ACID (subclass of nutritional supplementation)
- [x] - FIRST GENERATION SULFONYLUREAS (insulin stimulating agents)
- [x] - SECOND GENERATION SURLFONYLUREAS (insulin stimulating agents)
- [x] - HMG COA REDUCTASE INHIBITORS (STATINS)
- [x] - WEIGHT LOSS DRUGS
- [x] - XANTHINE OXIDASE INHIBITORS (subclass of anti-gout agent)
- [x] - Uricosurics (subclass of anti-gout agent)
- [x] - ADP receptor inhibitor (subclass of platelet aggregation inhibitor)
- [x] - antiarrythmic classes 1A, 1B, 1C, and 3. (subclasses of antiarrythmic)
- [x] - thiazide diuretic (subclass of diuretic)

**Comment by LCCarmody** [comment]
The answer is *some*.  We have a pharmacotherapy (MAXO_0000058)  branch which has to the level of beta blockers (listed as a synonym, but the label is MAXO_0000187 beta-adrenergic antagonist agents).  We will not have each individual drug.  We are currently using xrefs to CHEBI classes which usually uses this term as 'has_role' to annotate the drug.  

We are looking at also xref to RXNorm and/or SNOMED-CT, but that will take some time.  Please take a look at the branch.  
ANy ideas how to reference drugs/xref, etc. is welcome.

**Comment by diatomsRcool** [comment]
I went through my list and what is listed above is what I think could be added to MAXO. Should I add a bunch of NTRs?

**Comment by LCCarmody** [comment]
Not sure how we will handle this. Talked about doing some sort of annotation file or something. 
 Some of these terms are present but maybe need to be updated with synonyms.  @matentzn @pnrobinson Thoughts?

As for NTR, probably just add markdown check boxes maybe?  i.e., - [ ]

**Comment by LCCarmody** [comment]
Not sure why it isn't working. NM.

**Comment by diatomsRcool** [comment]
It is very likely that some of these are already there and I just couldn't find them.

**Comment by matentzn** [comment]
Please add this to our meeting minutes both of you; I am not sure what this ticket exactly is about :P Thanks. :)

**Comment by LCCarmody** [comment]
Already did. :)

**Comment by matentzn** [comment]
Hey all, I think it would be best if we broke this massive ticket down; @LCCarmody can you perhaps break down the list into "already there", "will do" and "prefer not to"; @diatomsRcool and I will then take the "prefer not to"s and see wether we can solve them in a post-composed fashion on the ECTO side.

**Comment by LCCarmody** [comment]
I guess none of the suggested terms are there.  Some are easier to add than others.

The definitely will add (and I will start a different ticket) are: 

Term   request | Possible term label | XREF | Notes
-- | -- | -- | --
hormone   replacement therapy* |   |   | See ticket:   https://github.com/monarch-initiative/MAxO/issues/101
ACE   inhibitor |   |   |  
BILE-ACID SEQUESTRANTS | Bile acid sequestrant antilipemic agent | SNOMEDCT:372872006, NCIT:C98148 | Familial   Hypercholesterolemia.
Fibrates | Fibrate antilipidemic agent,   fibrate antihyperlipidemic agent | NCIT:C98150, SCTID: 372514009 |  
HMG COA   REDUCTASE INHIBITORS (STATINS) | Statin or HMG-CoA Reductase   Inhibitor | CHEBI:87631, SCTID: 315053001,   NCIT:C1655 |  
  |   |   |  
niacin   therapy |   |   |  
potassium   supplements |   |   |  
potassium-sparing   agents | potassium-sparing diuretic   agents | SCTID: 372753003, NCIT:C49186, |  
LOOP DIURETICS |   |   |  
nicotinic   acid |   |   |  
FIRST GENERATION SULFONYLUREAS, SECOND   GENERATION SULFONYLUREAS | Sulfonylurea Antidiabetic Agent | NCIT:C97936, SCTID: 432955007,   SCTID: 372711004, CHEBI:76983 | Will not distinguish 1st/2nd   generation sulfonureas
Uricosurics | Uricosuric agent | NCIT:C921, CHEBI:35841, SCTID: 372758007,   SCTID: 773923003
thiazide diuretic | thiazide diuretic agent | SCTID: 372747003, CHEBI:50264,   NCIT:C49185 |  


These are a possibility, but will need to think further on it:

Term   request | Possible term label | XREF | Notes
-- | -- | -- | --
aspirin   therapy |   |  
BENZODIAZEPINES |  
XANTHINE OXIDASE INHIBITORS | SCTID:   419262004, NCIT:C1637
ADP receptor inhibitor | Possibly, I see the wikipedia page, but I do not find anything in SNOMED   or much in other ontologies (NCIT, CHEBI, etc).  Could you give PMID sources with this   usage?  This may fall under 'not a   priority' because it is not a treatment for rare disease.




The will not add at this time are:

Term   request | Possible term label | XREF | Notes
-- | -- | -- | --
ALPHA-GLUCOSIDASE INHIBITORS |   |   |  
T-TYPE CALCIUM-CHANNEL BLOCKER |   |   |  
SLOW-RELEASE DIHYDROPYRIDINES OTHER THAN   NIFEDIPINE OR AMLOPIDINE (L-type calcium channel blocker |   |   |  
Erectile   dysfunction drugs | Unsure, this would fall under   PDE5 inhibitors or some category? |   |  
K-CHANNEL BLOCKERS |   |   |  
Weight   loss drugs |   |   |  
antiarrythmic classes 1A, 1B, 1C, and 3. |   |

**Comment by matentzn** [comment]
Awesome, thanks @LCCarmody 

One thing I would like to make very sure of is that we are careful that *everything in MAXO is an action* and should be labelled as such. You can justify the term "therapy" under clincal action, but say `potassium supplements` is clearly not; we do not want to start confusing people with maxo terms that sound like drugs.

In general, @LCCarmody, you should make sure that every single term label can be without doubt understood as an action, and not as a material entity such as some food item or a drug (to be confused then with other terminologies). Does that sound right?

@diatomsRcool If you move the table of "not add" as NTRs to ECTO, we can create pre-composed terms for those!

**Comment by LCCarmody** [comment]
@matentzn sorry, I got sloppy. It should be 'potassium supplementation'--although I will do further research to see if it is referred to by any other phrase in scientific literature first (I did a cursory look yesterday, but I will do so more in-depth before adding each term).
